### PR TITLE
Change amount format

### PR DESCRIPTION
**Pull request by Andrei-Dolgolev**
## Changes

Add raw_amount column to database.
Migrate all amount to correct string amount format.
Extend all responses from GET `/drops` and GET `/drops/batch` to return database amount and string_amount

### CODE REVIEW

**Comment by kellan-simiotics** [comment]
@Andrei-Dolgolev I pushed a fix for the UI to handle raw_amount. Please review.

**Comment by zomglings** [comment]
@bugout-dev check
- [ ] Crypto Unicorns claim site uses new frontend
- [ ] Inform users about amount changes in input.

**Comment by zomglings** [comment]
@bugout-dev check
- [ ] Working script (logically correct with no assumptions about data in database) to populate `raw_amount` column in `dropper_claimants`
- [ ] Checklist for deployment, to be approved by @kompotkot

**Comment by Andrei-Dolgolev** [comment]
Deplyment checks:
- [ ] 1) Run migration `alembic.sh -c alembic.prod.ini upgrade head` before deploy. Check if in database apear `raw_amount` column.
- [ ] 2) Run python -m engineapi.scripts.fill_raw_amount fill_raw_amount in production enviroment.
- [ ] 3) Check if it's looks correct 
```sql
select amount, raw_amount, temptest.token_type, temptest.claim_id 
from dropper_claimants
inner join dropper_claims on dropper_claimants.dropper_claim_id = dropper_claims.id
inner join temptest on temptest.claim_id::int = dropper_claims.claim_id;
```
- [ ] 4) Drop  temptest table if all looks correct.
- [ ] 5) Merge requiest to main and deploy.
- [ ] 6) Test add/update claimants and signature.

**Pull request merged**
